GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/647738d5a42e2433628cc369
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Arrgrrto Hellas",
    "number": "0423-14223456"
}
###
PUT http://localhost:3001/api/persons/6479be5e5b45f404184b560e
content-type: application/json

{
    "name": "Arrgrrto Hellas",
    "number": "1230423-14223456"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "0423-14223456"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "",
    "number": "0423-14223456"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "sdasda",
    "number": ""
}
###
POST https://pbookcem.fly.dev/api/persons
content-type: application/json

{
    "name": "sdasda",
    "number": ""
}
###
POST https://pbookcem.fly.dev/api/persons
content-type: application/json

{
    "name": "Ar23to Hellas",
    "number": "0423-14223456"
}
###
GET https://pbookcem.fly.dev/api/persons
###
DELETE http://localhost:3001/api/persons/6479cdfc58d42047360c67bb
###
DELETE https://pbookcem.fly.dev/api/persons/6479ca3fb47cd850f93bba06