GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/64772c7b0a0dd234838dba5a3bb
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Arrrrto Hellas",
    "number": "0423-14223456"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "0423-14223456"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "",
    "number": "0423-14223456"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "sdasda",
    "number": ""
}
###
POST https://pbookcem.fly.dev/api/persons
content-type: application/json

{
    "name": "sdasda",
    "number": ""
}
###
POST https://pbookcem.fly.dev/api/persons
content-type: application/json

{
    "name": "Ar23to Hellas",
    "number": "0423-14223456"
}
###
GET https://pbookcem.fly.dev/api/persons