GET http://localhost:3001/api/blogs/
###
POST http://localhost:3001/api/blogs/
content-type: application/json

{
    "title": "Test Title1",
    "author": "Tester Author1",
    "url": "http://www.test.com",
    "likes": 1
    
}